# AGI Script mapping
tcpAddress: "localhost:4573"
login:
  apiEndpoint: "http://payment.sisvietnam.vn/gis/restful/callcenter/login"
  usename: "sangoma"
  password: "hXKv_ngMEZK$vE8*@55aNYP#"
notify:
  apiEndpoint: "http://payment.sisvietnam.vn/gis/restful/callcenter/webhook/updateCallInfo"
