# Endpoint for connect to application
roaming-checker:
  port: 1330

# Operators
84005:
  apiEndpoint: "https://hub.vietnamobile.com.vn/vncert/roaming/check"
  clientID: VNPT
  privateKey: HgKtYe8S$4e09f2088c3518db35e92972bc341fdbfca9baf591add1559182830d894a0084
  apiKey: eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjZHMucm9hbWluZ0BjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImNkcy5yb2FtaW5nIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IlVubGltaXRlZCIsIm5hbWUiOiJEZWZhdWx0QXBwbGljYXRpb24iLCJpZCI6MjIsInV1aWQiOiI3NWZkYjNiMS1jNDU5LTRiZTctYWU0OS1kNmMxZGU2MDQ0NjkifSwiaXNzIjoiaHR0cHM6XC9cLzEwLjE1NS4xMzQuMTk4Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6bnVsbH19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInBlcm1pdHRlZFJlZmVyZXIiOiIiLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJSb2FtaW5nIiwiY29udGV4dCI6IlwvYXBpXC9yb2FtaW5nXC92MS4wLjAiLCJwdWJsaXNoZXIiOiJhZG1pbiIsInZlcnNpb24iOiJ2MS4wLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn1dLCJwZXJtaXR0ZWRJUCI6IiIsImlhdCI6MTYwMTk3ODg1NywianRpIjoiN2QyMTE0MzEtY2VmNC00MWRmLWE4OGMtMmU5YTIzZmMxNWJiIn0=.PVfim4bfBVd3_uVUS0ljJmO0j_tUvwYxQVWJ02md9Da-JYpRidbC3YrvQrBvTimI8QTSjrUGrFQGvCgcgyFJ819p5pZ69yF7nkIlGOMXeUkCCf8g31g-YJdUVXZI9l-lpM_uUSq1yx_Fv2hg3IbEiO31W2iJI8RhCRxU5EoC7pxp3nRkAyzvNOktushc7jHghG3vxKn7FjsQ5ONpnew9adP54DVascUBKlMVrIc6jWB6MFYECHc3BYa9GkjyO7Jg8_USVyziBMOqSkRj4YWWzT10tABc6Z7x9JJ5RoDmpm5xU3Fj_-plkhXmqLE_pfT0S20yUs5b1Lf4ZWg-lFwn7A==

84004:
  apiEndpoint: "https://roaminggw.viettel.vn:8800/api/roaming/checkMsisdn"
  clientID: VNPT
  privateKey: db622dfabf42b9b5eeec64ab6e364af7f2cd5e516400387938263158365a1bba
  apiKey: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2bnB0IiwiYXVkIjoiMTIzcXdlUVdFIiwiZXhwIjozNzYwMjU2MzM0MCwiaWF0IjoxNjAyNTYzMzQwfQ.Nd5M6a3aXS_dsg8XIzKxPMZRScNMjbIIgk1-xBcCizA3DoY58IkRiKjRA0pCWM0HcObTiO3jBlyYbHkoPa84Ug

84006:
  apiEndpoint: "https://roaminggw.viettel.vn:8800/api/roaming/checkMsisdn"
  clientID: VNPT
  privateKey: db622dfabf42b9b5eeec64ab6e364af7f2cd5e516400387938263158365a1bba
  apiKey: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2bnB0IiwiYXVkIjoiMTIzcXdlUVdFIiwiZXhwIjozNzYwMjU2MzM0MCwiaWF0IjoxNjAyNTYzMzQwfQ.Nd5M6a3aXS_dsg8XIzKxPMZRScNMjbIIgk1-xBcCizA3DoY58IkRiKjRA0pCWM0HcObTiO3jBlyYbHkoPa84Ug

84008:
  apiEndpoint: "https://roaminggw.viettel.vn:8800/api/roaming/checkMsisdn"
  clientID: VNPT
  privateKey: db622dfabf42b9b5eeec64ab6e364af7f2cd5e516400387938263158365a1bba
  apiKey: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2bnB0IiwiYXVkIjoiMTIzcXdlUVdFIiwiZXhwIjozNzYwMjU2MzM0MCwiaWF0IjoxNjAyNTYzMzQwfQ.Nd5M6a3aXS_dsg8XIzKxPMZRScNMjbIIgk1-xBcCizA3DoY58IkRiKjRA0pCWM0HcObTiO3jBlyYbHkoPa84Ug

84001:
  apiEndpoint: "https://info.mobifone.vn/roaming/check"
  clientID: VNPT
  privateKey: SeKDVrSjNwKVmPeVLvxNxT59e1an0FJT
  apiKey:

84002:
  apiEndpoint: "http://mnp_api.vnpt.vn/mapi/services/check_mnp_sub"
  clientID: VNPT
  privateKey: 
  apiKey:

database:
  user: asterisk
  password: asterisk
  name: asterisk
  host: 127.0.0.1
  port: 5432
  sslmode: disable
  timezone: Asia/Ho_Chi_Minh

redis:
  address: localhost:6379
  password: ""
  db: 0
  timeout: 120000

isRoaming:
  0: 400
  1: 200
  2: 502